"""empty message

Revision ID: 00e2ebcc7ddc
Revises: f864d47e2347
Create Date: 2016-03-16 13:35:43.292232

"""

# revision identifiers, used by Alembic.
revision = '00e2ebcc7ddc'
down_revision = 'f864d47e2347'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
