"""empty message

Revision ID: 0580b0b06946
Revises: 0a7301b60f3c
Create Date: 2016-03-16 13:24:34.155249

"""

# revision identifiers, used by Alembic.
revision = '0580b0b06946'
down_revision = '0a7301b60f3c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('disabled', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'disabled')
    ### end Alembic commands ###
