"""empty message

Revision ID: 0a7301b60f3c
Revises: 2580663da150
Create Date: 2016-03-16 13:22:20.113164

"""

# revision identifiers, used by Alembic.
revision = '0a7301b60f3c'
down_revision = '2580663da150'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
