"""empty message

Revision ID: 102ea692bfcf
Revises: 614c1d90428e
Create Date: 2017-02-09 14:20:48.103954

"""

# revision identifiers, used by Alembic.
revision = '102ea692bfcf'
down_revision = '614c1d90428e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('disable_captcha', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'disable_captcha')
    ### end Alembic commands ###
