"""empty message

Revision ID: 24e4f70e81de
Revises: 325b88f66322
Create Date: 2015-02-03 14:17:36.714127

"""

# revision identifiers, used by Alembic.
revision = '24e4f70e81de'
down_revision = '325b88f66322'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # create hstore -- will work on heroku postgres, but not on local databases.
    op.execute('CREATE EXTENSION IF NOT EXISTS hstore;')

    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('data', postgresql.HSTORE(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissions')
    ### end Alembic commands ###
