"""submissions with JSON

Revision ID: 2e9211b464fd
Revises: 325b88f66322
Create Date: 2015-02-17 11:59:37.287156

"""

# revision identifiers, used by Alembic.
revision = '2e9211b464fd'
down_revision = '325b88f66322'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('data', postgresql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissions')
    ### end Alembic commands ###
