"""empty message

Revision ID: 3ddf84fb2826
Revises: f99d5e2ab036
Create Date: 2018-01-14 23:02:30.007139

"""

# revision identifiers, used by Alembic.
revision = '3ddf84fb2826'
down_revision = 'f99d5e2ab036'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invoice_address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'invoice_address')
    # ### end Alembic commands ###
