"""add stripe_id to users column

Revision ID: 4b95d8299c89
Revises: 2e9211b464fd
Create Date: 2015-03-15 09:54:09.069667

"""

# revision identifiers, used by Alembic.
revision = '4b95d8299c89'
down_revision = '2e9211b464fd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_id', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stripe_id')
    ### end Alembic commands ###
