"""submissions cannot have a null form_id

Revision ID: 4e177d75b62f
Revises: 2580663da150
Create Date: 2015-10-06 21:07:21.018776

"""

# revision identifiers, used by Alembic.
revision = '4e177d75b62f'
down_revision = '2580663da150'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'form_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'form_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
