"""empty message

Revision ID: 745fe4b160a3
Revises: 102ea692bfcf
Create Date: 2017-02-09 14:26:39.069277

"""

# revision identifiers, used by Alembic.
revision = '745fe4b160a3'
down_revision = '102ea692bfcf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('captcha_disabled', sa.Boolean(), nullable=True))
    op.drop_column('forms', 'disable_captcha')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('disable_captcha', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('forms', 'captcha_disabled')
    ### end Alembic commands ###
