"""empty message

Revision ID: a156683c29f2
Revises: 3ddf84fb2826
Create Date: 2018-03-16 12:42:06.230652

"""

# revision identifiers, used by Alembic.
revision = 'a156683c29f2'
down_revision = '3ddf84fb2826'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('disable_email', sa.Boolean(), nullable=True))
    op.add_column('forms', sa.Column('disable_storage', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'disable_storage')
    op.drop_column('forms', 'disable_email')
    # ### end Alembic commands ###
