"""empty message

Revision ID: cb8e84c671bd
Revises: a156683c29f2
Create Date: 2018-05-09 17:05:16.974326

"""

# revision identifiers, used by Alembic.
revision = 'cb8e84c671bd'
down_revision = 'a156683c29f2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('session_token', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'session_token')
    op.drop_column('users', 'disabled')
    # ### end Alembic commands ###
