"""empty message

Revision ID: ddc6ebdafc1e
Revises: 0580b0b06946
Create Date: 2016-03-16 13:27:36.133423

"""

# revision identifiers, used by Alembic.
revision = 'ddc6ebdafc1e'
down_revision = '0580b0b06946'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.drop_column('forms', 'disabled')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('forms', 'enabled')
    ### end Alembic commands ###
