"""empty message

Revision ID: f864d47e2347
Revises: ddc6ebdafc1e
Create Date: 2016-03-16 13:35:40.052668

"""

# revision identifiers, used by Alembic.
revision = 'f864d47e2347'
down_revision = 'ddc6ebdafc1e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.drop_column('forms', 'enabled')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('forms', 'disabled')
    ### end Alembic commands ###
